src/basic_ui.h

Allow Tab Entry in Print Continuity Editor

---

build-macos/dmg_maker.sh
build-macos/homeview_dmg_maker.sh

updating dmg builder to use Release.

updating dmg builder to use Release.

---

src/animation_view.cpp
src/animation_view.h
src/calchartapp.h
src/cc_command.cpp
src/cc_preferences_ui.cpp
src/confgr.cpp
src/core/modes.cpp
src/core/modes.h
src/draw.cpp
src/draw.h
src/field_view.cpp
src/single_instance_ipc.cpp

Fix reset cached mode values

---

README-MACOSX.txt
README-UBUNTU.txt
README-WINDOWS.txt
build-macos/CalChart.xcodeproj/project.pbxproj
build-win/CalChart/CalChart.vcxproj

We plan to use the Boost Property Tree library to import/export CalChart Viewer JSON files.
This pull request isn't quite complete yet. @rmpowell77 would you mind updating the Mac readme and project files to link to Boost?

Bring Back Boost

---

scripts/osx-setup.sh

A script that should automatically install all of CalChart's dependencies on a Mac.

Mac Setup Script

---

src/cc_preferences_ui.cpp

Adding scroll preference.

---

src/top_frame.cpp

Updating the authors.

---

README-WINDOWS.md
src/calchartdoc.cpp
src/calchartdoc.h
src/core/animate.cpp
src/core/animate.h
src/core/cc_point.cpp
src/core/cc_point.h
src/core/cc_show.cpp
src/core/cc_show.h
src/field_view.cpp
src/setup_wizards.cpp
src/show_ui.cpp

Fixing up new show setup.  Columns to 1, no need for description.

Fix new show setup

---

src/calchartdoc.cpp
src/core/cc_sheet.cpp
src/core/cc_show.cpp

Viewer File Exporter: Format an Empty Array Where Manual Input is Required

---

build-macos/CalChart.xcodeproj/project.pbxproj
build-macos/calchart_cmd/main.cpp

linking up the right scheme so that somebody coming to calchart can build and run right away.

Addressing #207: Fixing up calchart_cmd so it builds

---

build-macos/CalChart.xcodeproj/project.pbxproj
src/core/cc_shapes.h
src/field_canvas.cpp
src/field_canvas.h
src/field_canvas_shapes.cpp
src/field_canvas_shapes.h

Snap to grid

---

src/calchartdoc.cpp
src/cc_command.cpp
src/core/cc_fileformat.h
src/core/cc_point.cpp
src/core/cc_point.h
src/core/cc_show.cpp
src/core/cc_show.h
src/draw.cpp
src/field_canvas.cpp
src/field_canvas_shapes.cpp
src/field_canvas_shapes.h
src/field_view.cpp
src/field_view.h

This should address #120 and #121 .

Work on saving current sheet and selection list.

---

src/show_ui.cpp
src/show_ui.h

Fix label warning

---

.gitmodules
build-macos/CalChart.xcodeproj/project.pbxproj
src/calchartdoc.cpp
src/calchartdoc.h
src/core/cc_show.cpp
src/core/cc_show.h
src/core/e7_transition_solver.cpp
src/core/e7_transition_solver.h
src/core/e7_transition_solver_ui.cpp
src/core/e7_transition_solver_ui.h
src/field_frame.cpp
src/field_frame.h
src/ui_enums.h

Revert "Revert "E7 Auto-Transition Algorithms""

---

src/core/animate.cpp
src/core/animatecompile.cpp
src/core/animatecompile.h
src/field_canvas.cpp

And some performance improvements.

Fix rotate

---

src/calchartdoc.cpp
src/calchartdoc.h
src/core/cc_show.cpp
src/core/cc_show.h
src/field_view.cpp

Use the same dot ratio for relabel as selecting points.

Fix for #236

---

src/core/cc_show.cpp

Reset reference points for only points selected.

Fix for #179

---

build-macos/CalChart.xcodeproj/project.pbxproj
src/core/cc_coord.h
src/core/cc_show.cpp
src/draw.cpp
src/field_canvas.cpp
src/field_canvas.h
src/field_frame.cpp
src/field_frame.h
src/field_frame_controls.cpp
src/field_frame_controls.h

Cleaning up the field view control bar.

---

src/field_canvas.cpp
src/field_canvas.h
src/field_frame.cpp
src/field_frame.h
src/field_frame_controls.cpp
src/field_frame_controls.h

Trying out adding two grid choices, one for the marchers, the other for the tool.
See video on the effect.

Fix for #252.  Adding a snap to grid for tools.

---

src/e7_transition_solver_ui.cpp

Add Scrolling/Resizing of Transition Solver Frame

---

src/ContinuityBrowser.cpp
src/ContinuityBrowser.h
src/ContinuityEditorPopup.cpp
src/ContinuityEditorPopup.h
src/FieldCanvas.cpp
src/FieldCanvas.h
src/FieldThumbnailBrowser.cpp
src/FieldThumbnailBrowser.h
src/FieldView.cpp
src/FieldView.h
src/basic_ui.cpp
src/basic_ui.h
src/calchartapp.cpp
src/field_frame.cpp
src/field_frame.h

Also change the way we name files, splitting out views.  Some small cleanup.

279: pressing on arrow keys doesn't fix up thumbnails.

---

CMakeLists.txt
src/field_frame.cpp
src/field_frame.h
src/field_frame_controls.cpp
src/field_frame_controls.h

Incorporating AUI, which is a dockable UI flavor of wxWidgets.

Work on aui

---

.gitmodules
CMakeLists.txt
src/CalChartApp.cpp
src/CalChartDoc.cpp
src/CalChartFrame.cpp
src/CalChartFrame.h
src/ColorPalette.cpp
src/ColorPalette.h
src/ColorSetupCanvas.cpp
src/ColorSetupCanvas.h
src/ColorSetupDialog.cpp
src/ColorSetupDialog.h
src/ContinuityEditorPopup.cpp
src/ContinuityEditorPopup.h
src/basic_ui.h
src/cc_preferences_ui.cpp
src/confgr.cpp
src/confgr.h
src/core/cc_continuity.cpp
src/core/cc_continuity.h
src/core/cc_parse_errors.h
src/field_frame_controls.cpp
src/ui_enums.h

Export and import color palette.

Better color palettes

---

src/draw.cpp

Fix for #2: Printing on windows looks horrible

---

CMakeLists.txt
src/FieldCanvas.cpp
src/FieldCanvas.h

Updating wxWidgets to 3.1.4.  Looks like it was an easy integration.

Updating to wxWidgets 3.1.4

---

CMakeLists.txt
README-MACOSX.md

Fixing up how we do mac builds for arm and x86 support.

---

CMakeLists.txt
calchart_cmd/main.cpp

Looks like this hasn't been touched in a while.  Cleaning it up.

Fixing up the calchart_cmd

---

CMakeLists.txt
src/SetupMarchers.cpp
src/core/CalChartAnimationErrors.h

Fixing up CMake so it works in make files.

issue #348: default cmake command produced: Could NOT find Threads

---

.github/workflows/cmake.yml
CMakeLists.txt

https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/

Trying out

---

README-architecture.md
README.md

updating the architecture guide.

---

.gitmodules
CMakeLists.txt
src/core/CalChartText.cpp
src/core/CalChartText.h
src/core/print_ps.cpp
src/core/print_ps.h
src/draw.cpp
src/draw.h
tests/CalChartContinuityTests.cpp
tests/CalChartCoordTests.cpp
tests/CalChartPointTests.cpp
tests/CalChartSheetTests.cpp
tests/CalChartShowTests.cpp
tests/CalChartTests.cpp
tests/CalChartTextTests.cpp
tests/PrintToPSTests.cpp

using catch2 as the test framework.

Issue #354: Incorporate ctest into calchart and cmake workflows

---

src/core/CalChartShapes.cpp
tests/CalChartShapesTests.cpp

making rectangle more normal.
Fixing unit tests.

Issue 418: Why does shape_rect have an extra +1 in it's size

---

src/CalChartDrawing.cpp
src/core/CalChartDrawCommand.h
src/core/CalChartShowMode.cpp

These were some compiler warnings that are easy to catch.

Fixing up some compiler warnings.

---

.clang-tidy
cmake/dependencies.cmake
src/AnimationPanel.cpp
src/AnimationPanel.h
src/CMakeLists.txt
src/CalChartSplash.cpp
src/PointPicker.cpp
src/PointPicker.h
src/PreferencesContCellSetup.cpp
src/PreferencesContCellSetup.h
src/PreferencesDrawingSetup.cpp
src/PreferencesDrawingSetup.h
src/PreferencesGeneralSetup.cpp
src/PreferencesGeneralSetup.h
src/PreferencesPSPrintingSetup.cpp
src/PreferencesShowModeSetup.cpp
src/PreferencesUtils.h
src/SetupMarchers.cpp
src/basic_ui.cpp
src/basic_ui.h
src/core/CalChartConstants.h

wxUI is a Declarative UI based on work done in basic_ui of CalChart.  We should start using that external package for the UI elements of CalChart.

Utilize wxUI

---

src/CMakeLists.txt
src/CalChartDrawing.cpp
src/CalChartDrawing.h
src/CalChartFrame.cpp
src/CalChartPreferences.cpp
src/PreferencesPrintContinuitySetup.cpp
src/PreferencesPrintContinuitySetup.h
src/PreferencesShowModeSetup.cpp
src/PrintContinuityEditor.cpp
src/PrintContinuityEditor.h
src/PrintContinuityPreview.cpp
src/PrintContinuityPreview.h

Allows for easier adjustment of the Print continuity look.

Adding Print Continuity preview.

---

src/CalChartDrawing.h
src/FieldCanvas.h
src/core/CalChartCoord.h
src/core/CalChartSelectTool.h

Part of the plan to make a simple calchart core.

Introducing a Coord basic.

---

.github/workflows/cmake.yml
ccvers.h.in
cmake/dependencies.cmake
src/AnimationView.cpp
src/CalChartDrawing.cpp
src/CalChartDrawing.h
src/CalChartView.cpp
src/CalChartView.h
src/ColorSetupCanvas.cpp
src/ColorSetupCanvas.h
src/FieldCanvas.cpp
src/FieldThumbnailBrowser.cpp
src/ShowModeSetupCanvas.cpp
src/core/CalChartAnimation.cpp
src/core/CalChartAnimation.h
src/core/CalChartAnimationCommand.cpp
src/core/CalChartAnimationCommand.h
src/core/CalChartDrawCommand.h
src/core/CalChartDrawPrimatives.h
src/core/CalChartFileFormat.h
src/core/CalChartPoint.cpp
src/core/CalChartShapes.cpp
src/core/CalChartShapes.h
src/core/CalChartUtils.h
tests/CalChartDrawCommandTests.cpp
tests/CalChartShapesTests.cpp
tests/CalChartShowModeTests.cpp

Moving more of the What to draw into CalChart Core and the how to draw into the CalChart UI portion. Introducing the use of ranges to allow easier transformation from Points to draw commands.

Restructuring CalChart drawing.

---

README-architecture.md
src/AnimationView.cpp
src/CalChartDrawing.cpp
src/CalChartDrawing.h
src/CalChartView.cpp
src/CalChartView.h
src/ColorSetupCanvas.cpp
src/ContinuityBoxDrawer.cpp
src/ContinuityBoxDrawer.h
src/CustomListViewPanel.cpp
src/CustomListViewPanel.h
src/FieldCanvas.cpp
src/FieldThumbnailBrowser.cpp
src/ShowModeSetupCanvas.cpp
src/core/CalChartAnimation.cpp
src/core/CalChartAnimation.h
src/core/CalChartAnimationCommand.cpp
src/core/CalChartAnimationCommand.h
src/core/CalChartDrawCommand.cpp
src/core/CalChartDrawCommand.h
src/core/CalChartPoint.cpp
src/core/CalChartPoint.h
src/core/CalChartShapes.cpp
src/core/CalChartShapes.h
src/core/CalChartShowMode.cpp
src/core/CalChartShowMode.h
tests/CalChartDrawCommandTests.cpp
tests/CalChartShapesTests.cpp
tests/CalChartShowModeTests.cpp

Updated Architecture readme section.

Update Architecture and use better namespaces

---

.github/workflows/cmake.yml
LATEST_RELEASE_NOTES.md
src/core/CalChartSheet.cpp

* Issue #468: Fix Linux reading of older files
* Adding automation tag information for branch.

Issue #468: Fix Linux reading of older files (#470)

---

LATEST_RELEASE_NOTES.md
ccvers.h.in
src/CalChartDoc.cpp
src/core/CalChartFileFormat.h
src/core/CalChartShow.cpp
src/core/CalChartTypes.h

Issue #478: Include something to let users know when they are opening an new version of show

---

LATEST_RELEASE_NOTES.md
src/core/CalChartAnimation.cpp
src/core/CalChartAnimation.h
src/core/CalChartAnimationCommand.cpp
src/core/CalChartAnimationCommand.h
src/core/CalChartAnimationCompile.cpp
src/core/CalChartAnimationCompile.h
src/core/CalChartAnimationSheet.cpp
src/core/CalChartAnimationSheet.h
src/core/CalChartContinuityToken.cpp
tests/CalChartAnimationCommandTests.cpp
tests/CalChartContinuityTokenTests.cpp

This builds on the previous work and has Animation Commands with the Start position and can take in a Beat.  This makes everything stateless and more const.

Issue #512: Animation commands should contain the position, not the beat

---

LATEST_RELEASE_NOTES.md
calchart_cmd/main.cpp
src/core/CalChartAnimation.cpp

Adding measurement to command compile step to confirm we do not have regressions

Issue #547: Add some basic profiling to calband_cmd

---

LATEST_RELEASE_NOTES.md
src/CalChartDrawing.cpp
src/CalChartDrawing.h
src/PrintContinuityPreview.cpp
src/core/CalChartShowMode.cpp
src/core/CalChartShowMode.h
src/core/CalChartUtils.h

Getting PDF printing to be more command based.

Issue #554: Move General printing over to PrintContUseNewDraw

---

LATEST_RELEASE_NOTES.md
src/CalChartDrawing.cpp
src/CalChartDrawingGetMinSize.h
src/StackDrawPlayground.cpp
src/StackDrawPlayground.h
src/core/CalChartDrawCommand.h

V and H stack need to apply addition at layout, not applying it to each element.

Issue #563: Print doesn't show continuity correct

---

src/AnimationView.cpp
src/CalChartDoc.h
src/CalChartSizes.h
src/CalChartView.h
src/FieldThumbnailBrowser.cpp
src/FieldThumbnailBrowser.h
src/PrintContinuityEditor.cpp
src/core/CalChartDrawCommand.h
src/core/CalChartDrawPrimatives.h
src/core/CalChartShow.cpp
src/core/CalChartShow.h

Part 2.
Moving the field from Browser to Show.

Issue #565: Move more drawing into Show and ShowDoc

---

.clang-tidy
src/CMakeLists.txt
src/CalChartDoc.cpp
src/CalChartDoc.h
src/CalChartFrame.cpp
src/CalChartFrame.h
src/CalChartView.cpp
src/CalChartView.h
src/EditCurveAssignments.cpp
src/EditCurveAssignments.hpp
src/FieldCanvas.cpp
src/FieldCanvas.h
src/PointPicker.cpp
src/core/CalChartAnimation.cpp
src/core/CalChartFileFormat.h
src/core/CalChartShapes.cpp
src/core/CalChartShapes.h
src/core/CalChartSheet.cpp
src/core/CalChartSheet.h
src/core/CalChartShow.cpp
src/core/CalChartShow.h
tests/CalChartShapesTests.cpp
tests/CalChartSheetTests.cpp

Adding ability to assign points to curves
Points get inserted to a curve and then you can move the curve. Unit tests restructured to have better coverage of sheets. It's so beautiful.

Issue #627: Need to have a curve assignment pop-up for managing order of points on a curve
